# theme = "heisenberg"
#theme = "catppuccin_latte"
theme = "catppuccin_mocha"
# theme = "everforest_dark"

[editor]
rulers = [80, 120]
line-number = "relative"
cursorline = true
bufferline = "multiple"
popup-border = "all"

[editor.smart-tab]
enable = false

[editor.lsp]
auto-signature-help = false

[editor.statusline]
left = ["version-control", "selections", "mode", "spinner", "file-type", "file-name", "diagnostics", "position", "position-percentage", "total-line-numbers", "read-only-indicator", "file-modification-indicator"]
right = ["file-encoding", "file-line-ending"]
mode.normal = "N"
mode.insert = "I"
mode.select = "V"


[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"G" = "goto_last_line"
"space" = { "q" = ":buffer-close" }
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
