[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true }}

[[language]]
name = "python"
auto-format = true
